refactorying folders && add pytests for cli
Signed-off-by: Jooho Lee <jlee@redhat.com>

diff --git a/tests/test-data/units/loopy/roles-test/non-cluster/shell-execute/config.yaml b/tests/test-data/units/loopy/roles-test/non-cluster/shell-execute/config.yaml
--- a/tests/test-data/units/loopy/roles-test/non-cluster/shell-execute/config.yaml
+++ b/tests/test-data/units/loopy/roles-test/non-cluster/shell-execute/config.yaml
@@ -2,43 +2,43 @@ unit:
   created_date: "20240221"
   description: This unit is to test role "shell-execute".
   steps: 
-    # - role:
-    #    name: shell-execute
-    #    description: "[TEST] Single Command"
-    #    input_env:
-    #      COMMANDS: |
-    #        echo "unit-role1-c1" 
+    - role:
+       name: shell-execute
+       description: "[TEST] Single Command"
+       input_env:
+         COMMANDS: |
+           echo "unit-role1-c1" 
 
-    # - role:
-    #    name: shell-execute
-    #    description: "[TEST] Multiple Commands without %%" 
-    #    input_env:
-    #      COMMANDS: |
-    #        echo "Test1" > /tmp/a.out 
-    #        cat /tmp/a.out
+    - role:
+       name: shell-execute
+       description: "[TEST] Multiple Commands without %%" 
+       input_env:
+         COMMANDS: |
+           echo "Test1" > /tmp/a.out 
+           cat /tmp/a.out
 
-    # - role:
-    #    name: shell-execute
-    #    description: "[TEST] Multiple Commands without %% using env" 
-    #    input_env:
-    #      COMMANDS: |
-    #         export text=Test2
-    #         echo $text > /tmp/a.out 
-    #         cat /tmp/a.out
-    #         echo ${text}
-    #         if [[ $(cat /tmp/a.out) != "${text}" ]]
-    #         then
-    #           echo "environment variable failed to pass to next command" 1>&2
-    #         fi
-    #      STOP_WHEN_FAILED: "true"
+    - role:
+       name: shell-execute
+       description: "[TEST] Multiple Commands without %% using env" 
+       input_env:
+         COMMANDS: |
+            export text=Test2
+            echo $text > /tmp/a.out 
+            cat /tmp/a.out
+            echo ${text}
+            if [[ $(cat /tmp/a.out) != "${text}" ]]
+            then
+              echo "environment variable failed to pass to next command" 1>&2
+            fi
+         STOP_WHEN_FAILED: "true"
 
-    # - role:
-    #    name: shell-execute
-    #    description: "[TEST] Multiple Commands with %%" 
-    #    input_env:
-    #      COMMANDS: |
-    #        echo "Test3" > /tmp/a.out %% cat /tmp/a.out
-    #      STOP_WHEN_FAILED: "true"
+    - role:
+       name: shell-execute
+       description: "[TEST] Multiple Commands with %%" 
+       input_env:
+         COMMANDS: |
+           echo "Test3" > /tmp/a.out %% cat /tmp/a.out
+         STOP_WHEN_FAILED: "true"
 
     - role:
        name: shell-execute
@@ -49,30 +49,30 @@ unit:
           cat /tmp/a.out
          STOP_WHEN_FAILED: "true"  
 
-    # - role:
-    #    name: shell-execute
-    #    description: "[TEST] Multiple Commands for statement"  
-    #    input_env:
-    #      COMMANDS: |      
-    #         for i in {1..5}; do
-    #             echo "$((i * 1000))"
-    #             sleep 1 
-    #         done
-    #      STOP_WHEN_FAILED: "true"  
-
-
     - role:
        name: shell-execute
-       description: "[TEST] Multiple Commands for statement with %%"  
+       description: "[TEST] Multiple Commands for statement"  
        input_env:
          COMMANDS: |      
-            echo "TEST"  %%
-            ## TEST 
-            for i in {1..2}; do
+            for i in {1..5}; do
                 echo "$((i * 1000))"
                 sleep 1 
             done
          STOP_WHEN_FAILED: "true"  
+
+
+    # - role:
+    #    name: shell-execute
+    #    description: "[TEST] Multiple Commands for statement with %%"  
+    #    input_env:
+    #      COMMANDS: |      
+    #         echo "TEST"  %%
+    #         ## TEST 
+    #         for i in {1..2}; do
+    #             echo "$((i * 1000))"
+    #             sleep 1 
+    #         done
+    #      STOP_WHEN_FAILED: "true"  
 
 #  - role:
 #        name: shell-execute
